import { test, expect } from '@fixtures/index';
import { Tag } from '@/types/testTags';
import { OWNER_PASSCODE } from '@data/static/staff';
import type { StaffIncomeStat } from '@pages/pos/IncomeStaffPage';

/**
 * Staff Income — `/incomes/income-staff`
 *
 * Generated by Skill 2 (linear-testcase-gen) from docs/testcases/income-staff-testcases.md.
 * Selectors come from a live Playwright MCP scan (2026-07-06).
 *
 * Two clusters:
 *   - Structural (TC-IST-01…12): verify layout/filter/permission against today's
 *     data — no seeding required (mirrors the Daily Sale Report "Cluster A").
 *   - Data-dependent (TC-IST-13…18, tagged [data]): assert the listing table +
 *     per-staff detail. These self-skip when the scanned day has no staff rows,
 *     so the suite stays green on an empty tenant/day.
 */

const USD = /^-?\$[\d,]+\.\d{2}$/;
const STAT_LABELS: StaffIncomeStat[] = [
  'Total staff',
  'Total orders',
  'Total subtotal',
  'Total supply fee',
  'Total tip',
  'Total staff income',
];

test.describe(`Staff Income — structure & permission ${Tag.REGRESSION}`, () => {
  test('TC-IST-01: opening the route shows the passcode dialog before data renders', async ({
    incomeStaffPage,
    passcodeDialog,
  }) => {
    await incomeStaffPage.goto();
    await passcodeDialog.waitForVisible();
    expect(await passcodeDialog.isOpen()).toBe(true);
  });

  test.describe('after unlock', () => {
    test.beforeEach(async ({ incomeStaffPage, passcodeDialog }) => {
      await incomeStaffPage.goto();
      await passcodeDialog.enterPasscode(OWNER_PASSCODE);
      await incomeStaffPage.waitForReady();
    });

    test('TC-IST-02: correct passcode unlocks and shows the "Staff Income" title', async ({
      incomeStaffPage,
    }) => {
      await expect(incomeStaffPage.heading).toBeVisible();
    });

    test('TC-IST-03: default filter is Today and the URL carries from/to', async ({ page }) => {
      await expect(page).toHaveURL(/from=\d+/);
      await expect(page).toHaveURL(/to=\d+/);
    });

    test('TC-IST-04: the aggregate bar shows all 6 stats', async ({ incomeStaffPage }) => {
      for (const label of STAT_LABELS) {
        await expect(incomeStaffPage.statLabel(label)).toBeVisible();
      }
    });

    test('TC-IST-05: the Search staff box accepts input', async ({ incomeStaffPage }) => {
      await expect(incomeStaffPage.searchInput).toBeVisible();
      await incomeStaffPage.searchStaff('Anna');
      await expect(incomeStaffPage.searchInput).toHaveValue('Anna');
    });

    test('TC-IST-06: period preset dropdown defaults to "Today"', async ({ incomeStaffPage }) => {
      expect(await incomeStaffPage.periodDropdownText()).toContain('Today');
    });

    test('TC-IST-07: the calendar button shows a MM/DD/YYYY date', async ({ page }) => {
      await expect(page.getByRole('button', { name: /\d{2}\/\d{2}\/\d{4}/ }).first()).toBeVisible();
    });

    test('TC-IST-08: detail panel is empty until a staff is selected', async ({
      incomeStaffPage,
    }) => {
      await expect(incomeStaffPage.noDetail).toBeVisible();
    });

    test('TC-IST-12: aggregate money stats render as $#,##0.00', async ({ incomeStaffPage }) => {
      for (const label of [
        'Total subtotal',
        'Total supply fee',
        'Total tip',
        'Total staff income',
      ] as const) {
        expect(await incomeStaffPage.readStatValue(label)).toMatch(USD);
      }
    });
  });
});

test.describe(`Staff Income — filter & URL ${Tag.REGRESSION}`, () => {
  test('TC-IST-09: a day with no staff shows "No results found." and zeroed totals', async ({
    incomeStaffPage,
    passcodeDialog,
  }) => {
    // Jump far into the past — a day almost certainly without staff activity.
    const emptyDay = new Date();
    emptyDay.setFullYear(emptyDay.getFullYear() - 3);
    await incomeStaffPage.gotoRange(emptyDay, emptyDay);
    if (await passcodeDialog.isOpen()) await passcodeDialog.enterPasscode(OWNER_PASSCODE);
    await incomeStaffPage.waitForReady();

    if (await incomeStaffPage.isEmpty()) {
      await expect(incomeStaffPage.emptyResults).toBeVisible();
      expect(await incomeStaffPage.readStatValue('Total staff')).toBe('0');
      expect(await incomeStaffPage.readStatValue('Total staff income')).toMatch(/^\$0\.00$/);
    } else {
      test.skip(
        true,
        'Chosen "empty" day unexpectedly had staff data — skipping empty-state assertions.',
      );
    }
  });

  test('TC-IST-10 + TC-IST-11: gotoDate updates from/to and survives reload', async ({
    incomeStaffPage,
    passcodeDialog,
    page,
  }) => {
    const past = new Date();
    past.setDate(past.getDate() - 7);
    await incomeStaffPage.gotoDate(past);
    if (await passcodeDialog.isOpen()) await passcodeDialog.enterPasscode(OWNER_PASSCODE);
    await incomeStaffPage.waitForReady();

    const urlBefore = new URL(page.url());
    const from = urlBefore.searchParams.get('from');
    expect(from).toBeTruthy();

    await page.reload({ waitUntil: 'domcontentloaded' });
    if (await passcodeDialog.isOpen()) await passcodeDialog.enterPasscode(OWNER_PASSCODE);
    await incomeStaffPage.waitForReady();
    expect(new URL(page.url()).searchParams.get('from')).toBe(from);
  });
});

test.describe(`Staff Income — data-dependent [data] ${Tag.REGRESSION}`, () => {
  test.beforeEach(async ({ incomeStaffPage, passcodeDialog }) => {
    await incomeStaffPage.goto();
    await passcodeDialog.enterPasscode(OWNER_PASSCODE);
    await incomeStaffPage.waitForReady();
  });

  test('TC-IST-13: staff listing exposes the 6 spec columns', async ({ incomeStaffPage }) => {
    test.skip((await incomeStaffPage.rowCount()) === 0, 'No staff rows for the current day.');
    const headers = (await incomeStaffPage.headerLabels()).join(' | ');
    for (const col of ['Staff', 'Orders', 'Subtotal', 'Supply', 'Tip', 'Total']) {
      expect(headers).toContain(col);
    }
  });

  test('TC-IST-14: search filters the listing by nickname', async ({ incomeStaffPage }) => {
    test.skip((await incomeStaffPage.rowCount()) === 0, 'No staff rows for the current day.');
    const first = await incomeStaffPage.readRow(0);
    await incomeStaffPage.searchStaff(first.staff.slice(0, 3));
    await expect(incomeStaffPage.tableRows().first()).toContainText(first.staff.slice(0, 3));
  });

  test('TC-IST-15: clicking a staff opens the detail panel with Print enabled', async ({
    incomeStaffPage,
  }) => {
    test.skip((await incomeStaffPage.rowCount()) === 0, 'No staff rows for the current day.');
    await incomeStaffPage.openStaffDetail(0);
    await expect(incomeStaffPage.printButton).toBeEnabled();
  });

  test('TC-IST-18: Total staff income equals the sum of each staff Total Income', async ({
    incomeStaffPage,
  }) => {
    const count = await incomeStaffPage.rowCount();
    test.skip(count === 0, 'No staff rows for the current day.');
    const toCents = (s: string): number =>
      Math.round(parseFloat(s.replace(/[^0-9.-]/g, '')) * 100) || 0;
    let sum = 0;
    for (let i = 0; i < count; i++) sum += toCents((await incomeStaffPage.readRow(i)).totalIncome);
    const total = toCents(await incomeStaffPage.readStatValue('Total staff income'));
    expect(total).toBe(sum);
  });
});
